(ns skeptic.analysis.bridge.localize
  (:require [skeptic.analysis.schema-base :as sb]
            [skeptic.analysis.types :as at]))

(def ^:dynamic *error-context*
  nil)

(defn compact-context-map
  [m]
  (into {}
        (remove (comp nil? val))
        m))

(defmacro with-error-context
  [context & body]
  `(binding [*error-context* (merge *error-context*
                                    (compact-context-map ~context))]
     ~@body))

(defn localize-schema-value*
  [value seen-vars]
  (cond
    (nil? value) nil
    (at/same-class-name? value "clojure.lang.Var$Unbound")
    (localize-schema-value* (at/read-instance-field value "v") seen-vars)
    (instance? clojure.lang.Var value)
    (let [var-ref (or (sb/qualified-var-symbol value) value)]
      (cond
        (contains? seen-vars var-ref) (sb/placeholder-schema var-ref)
        (bound? value) (localize-schema-value* @value (conj seen-vars var-ref))
        :else (sb/placeholder-schema var-ref)))
    (sb/bottom-schema? value) sb/Bottom
    (sb/join? value)
    (apply sb/join (map #(localize-schema-value* % seen-vars) (:schemas value)))
    (at/same-class-name? value "skeptic.analysis.schema.Join")
    (apply sb/join (map #(localize-schema-value* % seen-vars)
                     (at/read-instance-field value "schemas")))
    (sb/valued-schema? value)
    (sb/valued-schema (localize-schema-value* (:schema value) seen-vars)
                   (localize-schema-value* (:value value) seen-vars))
    (at/same-class-name? value "skeptic.analysis.schema.ValuedSchema")
    (sb/valued-schema (localize-schema-value* (at/read-instance-field value "schema") seen-vars)
                   (localize-schema-value* (at/read-instance-field value "value") seen-vars))
    (sb/variable? value)
    (sb/variable (localize-schema-value* (:schema value) seen-vars))
    (at/same-class-name? value "skeptic.analysis.schema.Variable")
    (sb/variable (localize-schema-value* (at/read-instance-field value "schema") seen-vars))
    (at/dyn-type? value) at/Dyn
    (at/bottom-type? value) at/BottomType
    (at/ground-type? value)
    (at/->GroundT (:ground value) (:display-form value))
    (at/same-class-name? value "skeptic.analysis.schema.GroundT")
    (at/->GroundT (at/read-instance-field value "ground")
               (at/read-instance-field value "display_form"))
    (at/refinement-type? value)
    (at/->RefinementT (localize-schema-value* (:base value) seen-vars)
                   (:display-form value)
                   (:accepts? value)
                   (localize-schema-value* (:adapter-data value) seen-vars))
    (at/adapter-leaf-type? value)
    (at/->AdapterLeafT (:adapter value)
                    (:display-form value)
                    (:accepts? value)
                    (localize-schema-value* (:adapter-data value) seen-vars))
    (at/optional-key-type? value)
    (at/->OptionalKeyT (localize-schema-value* (:inner value) seen-vars))
    (at/fn-method-type? value)
    (at/->FnMethodT (localize-schema-value* (:inputs value) seen-vars)
                 (localize-schema-value* (:output value) seen-vars)
                 (:min-arity value)
                 (:variadic? value))
    (at/same-class-name? value "skeptic.analysis.schema.FnMethodT")
    (at/->FnMethodT (localize-schema-value* (at/read-instance-field value "inputs") seen-vars)
                 (localize-schema-value* (at/read-instance-field value "output") seen-vars)
                 (at/read-instance-field value "min_arity")
                 (at/read-instance-field value "variadic_QMARK_"))
    (at/fun-type? value)
    (at/->FunT (localize-schema-value* (:methods value) seen-vars))
    (at/same-class-name? value "skeptic.analysis.schema.FunT")
    (at/->FunT (localize-schema-value* (at/read-instance-field value "methods") seen-vars))
    (at/maybe-type? value)
    (at/->MaybeT (localize-schema-value* (:inner value) seen-vars))
    (at/same-class-name? value "skeptic.analysis.schema.MaybeT")
    (at/->MaybeT (localize-schema-value* (at/read-instance-field value "inner") seen-vars))
    (at/union-type? value)
    (at/->UnionT (localize-schema-value* (:members value) seen-vars))
    (at/same-class-name? value "skeptic.analysis.schema.UnionT")
    (at/->UnionT (localize-schema-value* (at/read-instance-field value "members") seen-vars))
    (at/intersection-type? value)
    (at/->IntersectionT (localize-schema-value* (:members value) seen-vars))
    (at/same-class-name? value "skeptic.analysis.schema.IntersectionT")
    (at/->IntersectionT (localize-schema-value* (at/read-instance-field value "members") seen-vars))
    (at/map-type? value)
    (at/->MapT (localize-schema-value* (:entries value) seen-vars))
    (at/same-class-name? value "skeptic.analysis.schema.MapT")
    (at/->MapT (localize-schema-value* (at/read-instance-field value "entries") seen-vars))
    (at/vector-type? value)
    (at/->VectorT (localize-schema-value* (:items value) seen-vars)
               (:homogeneous? value))
    (at/same-class-name? value "skeptic.analysis.schema.VectorT")
    (at/->VectorT (localize-schema-value* (at/read-instance-field value "items") seen-vars)
               (at/read-instance-field value "homogeneous_QMARK_"))
    (at/set-type? value)
    (at/->SetT (localize-schema-value* (:members value) seen-vars)
            (:homogeneous? value))
    (at/same-class-name? value "skeptic.analysis.schema.SetT")
    (at/->SetT (localize-schema-value* (at/read-instance-field value "members") seen-vars)
            (at/read-instance-field value "homogeneous_QMARK_"))
    (at/seq-type? value)
    (at/->SeqT (localize-schema-value* (:items value) seen-vars)
            (:homogeneous? value))
    (at/same-class-name? value "skeptic.analysis.schema.SeqT")
    (at/->SeqT (localize-schema-value* (at/read-instance-field value "items") seen-vars)
            (at/read-instance-field value "homogeneous_QMARK_"))
    (at/var-type? value)
    (at/->VarT (localize-schema-value* (:inner value) seen-vars))
    (at/same-class-name? value "skeptic.analysis.schema.VarT")
    (at/->VarT (localize-schema-value* (at/read-instance-field value "inner") seen-vars))
    (at/placeholder-type? value)
    (at/->PlaceholderT (localize-schema-value* (:ref value) seen-vars))
    (at/same-class-name? value "skeptic.analysis.schema.PlaceholderT")
    (at/->PlaceholderT (localize-schema-value* (at/read-instance-field value "ref") seen-vars))
    (at/value-type? value)
    (at/->ValueT (localize-schema-value* (:inner value) seen-vars)
              (localize-schema-value* (:value value) seen-vars))
    (at/same-class-name? value "skeptic.analysis.schema.ValueT")
    (at/->ValueT (localize-schema-value* (at/read-instance-field value "inner") seen-vars)
              (localize-schema-value* (at/read-instance-field value "value") seen-vars))
    (at/type-var-type? value)
    (at/->TypeVarT (:name value))
    (at/forall-type? value)
    (at/->ForallT (:binder value)
               (localize-schema-value* (:body value) seen-vars))
    (at/sealed-dyn-type? value)
    (at/->SealedDynT (localize-schema-value* (:ground value) seen-vars))
    (vector? value) (mapv #(localize-schema-value* % seen-vars) value)
    (set? value) (into #{} (map #(localize-schema-value* % seen-vars)) value)
    (and (map? value) (not (record? value)))
    (into {}
          (map (fn [[k v]]
                 [(localize-schema-value* k seen-vars)
                  (localize-schema-value* v seen-vars)]))
          value)
    (seq? value) (doall (map #(localize-schema-value* % seen-vars) value))
    :else value))

(defn localize-schema-value
  [value]
  (localize-schema-value* value #{}))
